# -*- coding: utf-8 -*-
"""Add_combinations.

Revision ID: 130784632737
Revises: 550ceb95fe1d
Create Date: 2022-04-30 11:35:45.567871

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "130784632737"
down_revision = "550ceb95fe1d"
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    colors_id = "colors.id"
    elements_id = "elements.id"
    names_id = "names.id"

    op.create_table(
        "combinations",
        sa.Column("card_shape_id", sa.Integer(), nullable=False),
        sa.Column("card_pattern_id", sa.Integer(), nullable=False),
        sa.Column("card_color_id", sa.Integer(), nullable=False),
        sa.Column("shirt_pattern_id", sa.Integer(), nullable=False),
        sa.Column("crest_shape_id", sa.Integer(), nullable=False),
        sa.Column("crest_pattern_id", sa.Integer(), nullable=False),
        sa.Column("crest_content_id", sa.Integer(), nullable=False),
        sa.Column("player_picture_id", sa.Integer(), nullable=False),
        sa.Column("first_name_id", sa.Integer(), nullable=False),
        sa.Column("last_name_id", sa.Integer(), nullable=False),
        sa.Column("country_flag_id", sa.Integer(), nullable=False),
        sa.Column("hair_color_id", sa.Integer(), nullable=False),
        sa.Column("eyes_color_id", sa.Integer(), nullable=False),
        sa.Column("skin_color_id", sa.Integer(), nullable=False),
        sa.Column("mouth_color_id", sa.Integer(), nullable=False),
        sa.Column("count", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["card_color_id"], [colors_id], ondelete="cascade"),
        sa.ForeignKeyConstraint(["card_pattern_id"], [elements_id], ondelete="cascade"),
        sa.ForeignKeyConstraint(["card_shape_id"], [elements_id], ondelete="cascade"),
        sa.ForeignKeyConstraint(
            ["country_flag_id"], ["countries.id"], ondelete="cascade"
        ),
        sa.ForeignKeyConstraint(
            ["crest_content_id"], [elements_id], ondelete="cascade"
        ),
        sa.ForeignKeyConstraint(
            ["crest_pattern_id"], [elements_id], ondelete="cascade"
        ),
        sa.ForeignKeyConstraint(["crest_shape_id"], [elements_id], ondelete="cascade"),
        sa.ForeignKeyConstraint(["eyes_color_id"], [colors_id], ondelete="cascade"),
        sa.ForeignKeyConstraint(["first_name_id"], [names_id], ondelete="cascade"),
        sa.ForeignKeyConstraint(["hair_color_id"], [colors_id], ondelete="cascade"),
        sa.ForeignKeyConstraint(["last_name_id"], [names_id], ondelete="cascade"),
        sa.ForeignKeyConstraint(["mouth_color_id"], [colors_id], ondelete="cascade"),
        sa.ForeignKeyConstraint(
            ["player_picture_id"], ["players.id"], ondelete="cascade"
        ),
        sa.ForeignKeyConstraint(
            ["shirt_pattern_id"], [elements_id], ondelete="cascade"
        ),
        sa.ForeignKeyConstraint(["skin_color_id"], [colors_id], ondelete="cascade"),
        sa.PrimaryKeyConstraint(
            "card_shape_id",
            "card_pattern_id",
            "card_color_id",
            "shirt_pattern_id",
            "crest_shape_id",
            "crest_pattern_id",
            "crest_content_id",
            "player_picture_id",
            "first_name_id",
            "last_name_id",
            "country_flag_id",
            "hair_color_id",
            "eyes_color_id",
            "skin_color_id",
            "mouth_color_id",
        ),
    )
    op.create_index(
        op.f("ix_combinations_count"), "combinations", ["count"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_combinations_count"), table_name="combinations")
    op.drop_table("combinations")
    # ### end Alembic commands ###
